export const SITE = {
  website: "https://argha.dev/",
  author: "Argha Ray",
  profile: "https://github.com/ArghaRay00",
  desc: "Argha Ray — software engineer in Bangalore. Backend systems, agent engineering, and notes from building real things.",
  title: "Argha Ray",
  ogImage: "og.png",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Kolkata",
} as const;
